version: '3'

services:
  web:
    build: ./web
    restart: always
    expose:
      - 80
    ports:
      - '80:80'
    links:
      - polls
    environment:
      - AXIOS_INSTANCE=${AXIOS_INSTANCE}
      - AXIOS_INSTANCE_AUTH=${AXIOS_INSTANCE_AUTH}
      - AXIOS_INSTANCE_POLL=${AXIOS_INSTANCE_POLL}
      - WEB_URL=${WEB_URL}
  polls:
    build: ./polls
    restart: always
    expose: 
      - 8083
    ports:
      - '8083:8083'
    environment:
      - DB_SERVER=${DB_SERVER}
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - '27017:27017'